### ISSUE TITLE
Base games which incl. update fail on titlekey

### ISSUE THREAD

**Issue by dnsBlah** [themoonisacheese/autoverif#8]
when I load up my own edump (using DBi) from Braid it fails on the decryption test already at titlekey.
<img width="574" alt="Screenshot 2024-09-10 at 08 09 30" src="https://github.com/user-attachments/assets/07d82613-778f-4d7f-9a7e-2c02e9bace40">

Braid's base game, already contains a update.
<img width="2213" alt="Screenshot 2024-09-10 at 08 08 54" src="https://github.com/user-attachments/assets/1ea3a1f6-7c9d-4a06-a0d7-82b72b7a3e31">

This similar issue happens with nxfileviewer, not only on this Braid base game, but also gamecards like https://github.com/Myster-Tee/NxFileViewer/issues/27

The issue must be in the underlying library used of the ticket validation.
How can I work around this?

**Comment by themoonisacheese** [comment]
Most likely this is a problem with nscb's title.keys file which is probably severely outdated as work on nscb stopped a long time ago.

https://github.com/julesontheroad/NSC_BUILDER

Having not touched verification code in more than a year, I won't be able to help you beyond telling you to move games you know are correct to your stash manually. Closing as wontfix.
